// ============================================================================
// Sherpa data model — core entity types
// ============================================================================
//
// This is the single source of truth for the shape of everything in the app.
// Every screen and every generation step reads from or writes to these types.
//
// Two architectural rules from the implementation brief are encoded here, so
// it's worth stating them up front because the types are designed around them:
//
//   1. FACTS vs JUDGMENT are separate. Anything checkable (a distance, a
//      transit time, whether a place exists) is a `VerifiedFact` sourced from
//      Google Maps or the hand-curated place-tier dataset — never invented by
//      an LLM. Claude only ever reasons over facts it is handed.
//
//   2. Legs and day-blocks are DERIVED from confirmed decisions by plain
//      application code, never authored independently and never generated by
//      an LLM. That is what makes "revisit a decision" safe and checkable.
//
// ----------------------------------------------------------------------------

// ============================================================================
// Shared enums / literal unions
// ============================================================================

/** Travel modes we ask Maps about. Direction matters for `flight` (wind/routing
 *  make Lisbon→Porto ≠ Porto→Lisbon), but not for `train`/`drive`. The FactCache
 *  uses this distinction to decide whether a place-pair key can be sorted. */
export type TransitMode = 'train' | 'drive' | 'flight' | 'transit' | 'walk'

/** How confident decision generation is in a stance. Computed against an
 *  explicit rubric in the system prompt — never self-reported by the model.
 *  `close_call` is expected to be the common case; an all-`high` decision set
 *  is itself a calibration warning. */
export type Confidence = 'high' | 'close_call' | 'worth_a_gut_check'

/** Lifecycle of a decision. `recommended` is what generation produces;
 *  the user moves it to `confirmed` (accepts) or `overridden` (picks the other
 *  stance). Only `confirmed`/`overridden` decisions feed leg generation. */
export type DecisionStatus = 'recommended' | 'confirmed' | 'overridden'

/** The four decision types in scope for v0 (single-region trips). Each type has
 *  its own fixed `stance` enum — see `DecisionStanceByType` below. */
export type DecisionType = 'base_city' | 'region_cut' | 'splurge_or_skip' | 'pace'

/** Place-tier classification — "how much time does this place genuinely
 *  deserve." Hand-curated in `place_tiers.md`, never fetched or LLM-generated. */
export type PlaceTier =
  | 'multi_day_city'
  | 'multi_day_region'
  | 'day_trippable'
  | 'half_day_stop'

/** Pace preference. Lives in two places by design: as a `trip_shape` prior
 *  (from the swipe quiz) and, once the user weighs in, as a confirmed `pace`
 *  decision. The confirmed decision wins. */
export type Pace = 'relaxed' | 'standard' | 'packed'

// ============================================================================
// Stance enums, keyed per decision type
// ============================================================================
//
// `stance` is the load-bearing field: every downstream renderer and the leg
// generator branch on it, so it must be a fixed enum, never free text.

export type BaseCityStance = 'split' | 'single'
/** `cut_<region>` — which secondary region to drop. v0 knows the two Portugal
 *  cases from the design examples; extend the union as the dataset grows. */
export type RegionCutStance = 'cut_algarve' | 'cut_porto' | 'cut_none'
export type SplurgeOrSkipStance = 'add' | 'skip'
export type PaceStance = Pace

/** Maps a decision type to its legal stance set, so TypeScript can enforce that
 *  a `base_city` decision never carries a `pace` stance, etc. */
export interface DecisionStanceByType {
  base_city: BaseCityStance
  region_cut: RegionCutStance
  splurge_or_skip: SplurgeOrSkipStance
  pace: PaceStance
}

/** Any legal stance string, regardless of decision type. */
export type AnyStance = DecisionStanceByType[DecisionType]

// ============================================================================
// Facts layer
// ============================================================================

/** A single checkable fact handed to Claude. Claude may cite these by
 *  `fact_id` but may never invent or alter the numbers. */
export interface VerifiedFact {
  fact_id: string
  type: 'transit_time' | 'place_tier' | 'place_metadata'
  /** Primary place the fact is about (single-place facts) or the origin
   *  (place-pair facts like transit time). */
  place: string
  /** Destination place for place-pair facts; omitted for single-place facts. */
  to?: string
  mode?: TransitMode
  /** Present on transit facts. */
  duration_minutes?: number
  /** Present on transit facts. */
  distance_meters?: number
  /** Present on place-tier facts. */
  tier?: PlaceTier
  /** Where the fact came from — used to keep provenance honest end to end. */
  source: 'google_distance_matrix' | 'google_places' | 'sherpa_place_heuristics'
}

/** A persisted FactCache row. NOTE: this is the ONLY entity that lives in the
 *  server-side store (Vercel KV). It is keyed purely by the fact identity —
 *  `(fact_type, place_a, place_b, mode)` — and carries NO trip_id or user_id,
 *  because "Lisbon to Porto by train" is one fact for everyone. See
 *  `caching_strategy.md` and `factCache.ts`. */
export interface FactCacheEntry {
  fact_type: VerifiedFact['type']
  place_a: string
  /** Null for single-place facts (e.g. place metadata). */
  place_b: string | null
  /** Null for single-place facts. */
  mode: TransitMode | null
  /** The cached payload (duration/distance/tier/etc). */
  value: Omit<VerifiedFact, 'fact_id'>
  /** Epoch ms when fetched — combined with TTL to decide staleness. */
  fetched_at: number
  /** TTL in ms (90 days for Tier-1 facts). */
  ttl_ms: number
}

// ============================================================================
// Trip + trip shape
// ============================================================================

/** The raw inputs that shape a trip: where, how long, and the traveler's
 *  leanings. `TripShapeInput` is the merge of swipe priors and explicit inputs
 *  (explicit always wins) — see `swipeMapping.ts`. */
export interface TripShapeInput {
  first_time: boolean
  /** Per-dimension prior values in the range -1..+1. Swipe-derived values are
   *  capped at ±0.6; explicit inputs may use the full range. */
  depth_breadth?: ShapeDimension
  pace?: ShapeDimension
  risk_tolerance?: ShapeDimension
  transit_tolerance?: ShapeDimension
  food_vs_culture?: ShapeDimension
  structure?: ShapeDimension
}

/** One trip-shape dimension's value plus where it came from. `source` matters:
 *  a `swipe` value may only break ties on non-`high` decisions, while an
 *  `explicit` value can carry real weight. */
export interface ShapeDimension {
  /** -1..+1. Sign encodes direction (see swipe_mapping.md agree_direction). */
  value: number
  source: 'swipe' | 'explicit'
  /** The swipe card that produced this, if any — kept for traceability. */
  card_id?: string
}

export interface Trip {
  id: string
  destination: string
  /** ISO date (YYYY-MM-DD). */
  start_date: string
  /** ISO date (YYYY-MM-DD). */
  end_date: string
  days_total: number
  trip_shape: TripShapeInput
  created_at: number
  updated_at: number
}

// ============================================================================
// Decisions
// ============================================================================

/** A generated/confirmed decision. The fields between `stance` and
 *  `facts_cited` come straight from Claude call #1 (decision_generation.md);
 *  `status` and `user_answer` are added by the app as the user engages. */
export interface Decision {
  id: string
  trip_id: string
  decision_type: DecisionType
  /** Fixed enum per decision_type — what downstream code branches on. */
  stance: AnyStance
  /** The stance in one plain sentence — shown big on the decisions screen. */
  headline: string
  /** 1–2 sentences. Must be tied to ≥1 fact in `facts_cited`. */
  reasoning: string
  /** The honest cost of this stance. Required, never empty. */
  tradeoff: string
  confidence: Confidence
  confidence_rationale: string
  /** fact_ids actually used. Empty + `confidence: high` is a generation
   *  failure, not a style issue. */
  facts_cited: string[]
  /** Decision types whose stance this one depends on / unlocks — the decision
   *  graph the leg generator reads (not just a flat list). */
  depends_on: DecisionType[]
  enables: DecisionType[]
  status: DecisionStatus
  /** The user's free-text or button answer in the ask-first flow, if given. */
  user_answer?: string
  created_at: number
  updated_at: number
}

/** An append-only audit row written on every decision change. This is what
 *  makes the revisit-a-decision impact preview possible: you need the prior
 *  state to diff the new one against. */
export interface DecisionHistory {
  id: string
  decision_id: string
  trip_id: string
  /** Snapshot of the decision's stance/status BEFORE the change. */
  prev_stance: AnyStance
  prev_status: DecisionStatus
  next_stance: AnyStance
  next_status: DecisionStatus
  changed_at: number
}

// ============================================================================
// Legs, transit edges, day-blocks (DERIVED — never authored by hand or LLM)
// ============================================================================

export type LegRole = 'primary' | 'secondary'

export interface Leg {
  id: string
  trip_id: string
  place: string
  role: LegRole
  nights: number
  /** Explicit ordering — legs are NOT ordered implicitly by creation time,
   *  because editing/reordering must be possible. */
  sequence_order: number
  /** True once a Document is attached to this leg (or one of its day-blocks).
   *  Uploading a booking and marking a leg "booked" are the same action. */
  locked: boolean
  /** The "why this leg is here" prose from the voice pass (Claude call #2).
   *  Added after structure exists; never alters the structure. */
  caption?: string
  created_at: number
}

export interface TransitEdge {
  id: string
  trip_id: string
  from_place: string
  to_place: string
  mode: TransitMode
  duration_minutes: number
  distance_meters?: number
  /** The VerifiedFact this edge's numbers came from — provenance, again. */
  fact_id: string
}

export type DayBlockKind = 'arrival' | 'explore' | 'day_trip' | 'open'

/** How a day-block came to exist. `generated` blocks can be regenerated when a
 *  decision changes; `manual` blocks are user hand-edits and must NOT be
 *  silently overwritten — that flag is the whole manual-edit-conflict guard. */
export type Provenance = 'generated' | 'manual'

export interface DayBlock {
  id: string
  trip_id: string
  leg_id: string
  kind: DayBlockKind
  /** Position within the leg (0-based). */
  order: number
  /** e.g. "Douro Valley" for a day_trip block. */
  target?: string
  /** Short hint from the generator, e.g. "light_day" for an arrival block. */
  note?: string
  /** The "why this is here" prose from the voice pass (Claude call #2).
   *  Added after structure exists; never alters the structure. */
  caption?: string
  provenance: Provenance
  /** True once a Document is attached to this specific block. */
  locked: boolean
}

// ============================================================================
// Documents
// ============================================================================

/** A tagged file on the shelf. v0 stores and tags only — NO parsing/extraction
 *  of contents. Attaching a document sets `locked = true` on its target. */
export interface TripDocument {
  id: string
  trip_id: string
  filename: string
  /** Stored file reference (data URL / object key). */
  ref: string
  /** Nullable: a document can be unattached and resolved later from the shelf.
   *  Exactly one of leg_id / day_block_id is set when attached. */
  leg_id: string | null
  day_block_id: string | null
  uploaded_at: number
}

// ============================================================================
// Aggregate: a fully-loaded trip as the UI consumes it
// ============================================================================

export interface TripBundle {
  trip: Trip
  decisions: Decision[]
  legs: Leg[]
  edges: TransitEdge[]
  day_blocks: DayBlock[]
  documents: TripDocument[]
  /** Append-only audit trail of decision changes — written whenever a settled
   *  decision is revisited and changed. Optional so bundles saved before this
   *  feature existed still load. This is the "before state" the revisit impact
   *  preview diffs against. */
  decision_history?: DecisionHistory[]
}
